version: "3.1"

services:
  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017

  api:
    build: .
    ports:
      - 3003:8080
    container_name: api
    depends_on:
      - db
